version: '3.7'

services:
  db:
    env_file: .env
    image: postgres:15-alpine
    container_name: $DATABASE_NAME
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
    volumes:
      - pgdata:/data/postgres
    # network_mode: host

  # app:
  #   build: .
  #   container_name: rentx
  #   restart: always
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/app
  #   network_mode: host

volumes:
  pgdata:
    driver: local
