version: '3.7'

services:
  db:
    image: postgres:15-alpine
    container_name: rentx_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=rentx_db
      - POSTGRES_DB=rentx_db
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  app:
    build: .
    container_name: rentx
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local
